### ISSUE TITLE
Using implicit solver together with Equinox raises `ad.CustomJVPException`

### ISSUE THREAD

**Issue by fhchl** [patrick-kidger/diffrax#135]
Hej! I am using diffrax together with equinox to fit ODE's to data. The following code works fine with the `Dopri5` solver, but throws an error for `Kvaerno3`:

    CustomJVPException: Detected differentiation of a custom_jvp function with respect to a closed-over value. That isn't supported because the custom JVP rule only specifies how to differentiate the custom_jvp function with respect to explicit input parameters. Try passing the closed-over value into the custom_jvp function as an argument, and adapting the custom_jvp rule.

I am not quite sure how to find out exactly which value is closed-over here.

Here is the somewhat minimal working example:

```python
import jax
import jax.numpy as jnp
import diffrax as dfx
import equinox as eqx
from scipy.optimize import least_squares


class ForwardModel(eqx.Module):
  params: float
  solver: dfx.AbstractSolver = eqx.static_field()

  def init(self, params, solver):
    self.params = params
    self.solver = solver

  def vector_field(self, x):
    return self.params*x

  def __call__(self, t, x0):
    vector_field = lambda t, x, _: self.vector_field(x)
    term = dfx.ODETerm(vector_field)
    sol = dfx.diffeqsolve(term, t0=t[0], t1=t[-1], dt0=t[1], y0=x0,
                        saveat=dfx.SaveAt(ts=t),
                        solver=self.solver,
                        stepsize_controller=dfx.PIDController(rtol=1e-3, atol=1e-6),
                        )
    return sol.ys


def fit(model: ForwardModel, t, y, x0):
  """Fit forward model via least squares."""
  init_params, treedef = jax.tree_flatten(model)

  def residuals(params):
    model = treedef.unflatten(params)
    return y - model(t, x0)

  fun = jax.jit(residuals)
  jac = jax.jit(jax.jacfwd(residuals))
  res = least_squares(fun, init_params, jac=jac)
  return treedef.unflatten(res.x)


# data and true model
t = jnp.linspace(0, 1, 100)
x0 = 1
true_model = ForwardModel(0.5, solver=dfx.Dopri5())
x_true = true_model(t, x0)

# Works
model = fit(ForwardModel(0.1, solver=dfx.Dopri5()), t, x_true, x0)
print(model)

# raises CustomJVPException
model = fit(ForwardModel(0.1, solver=dfx.Kvaerno3()), t, x_true, x0)
print(model)
```

**Comment by patrick-kidger** [comment]
So the problem here is the line `vector_field = lambda t, x, _: self.vector_field(x)`. Here you are capturing `self`, and thus also `self.params`, via closure.

Capturing JAX tracers via closures is usually fine. The one exception to this is around custom autodiff rules, which must receive all JAX tracers as arguments, and for which capturing via closure is verboten.

Meanwhile, `Kvaerno5` uses a custom autodiff rule: as an implicit diffeq solver it uses a nonlinear solver, and this uses the implicit function theorem to differentiate through its root finding operations. `Dopri5` doesn't do any of this as it's an explicit solver, which is why it doesn't raise an error; indeed with `Dopri5` what you've written is safe and above-board. (Incidentally you'd also get the same error if you tried to do e.g. `diffeqsolve(..., adjoint=BacksolveAdjoint())`, as again this involves custom autodiff.)

The simplest fix here is simply to define

```
class ForwardModel(eqx.Module):
    ...
    
    def vector_field(self, t, y, args):
        return self.params * x
        
        def __call__(self, t, x0):
            term = dfx.ODETerm(self.vector_field)
            ...
```
In this case `self` is a PyTree (as it's an Equinox module) so `self.vector_field` is also a PyTree (bound methods of Equinox modules are also PyTrees, with the implicit `self` as their only subnode), and so `self.param` isn't capture via closure any more: `diffeqsolve` can see the parameter because it's accessible descending through the PyTree: `term - self.vector_field - self - self.params`.

Generally this kind of complexity is something you only need to worry about once an error is raised, as you've found! Then go tracing through and figure out where you broke the PyTree structure. But this kind of complexity isn't something you should need to carry around in your head, as it should never break silently.

**Comment by fhchl** [comment]
Your answer fixes the issue _and_ explained to me some more of that JAX magic. Thank you! 

If one doesn't want to change the signature of `vector_field` and knowing that `self` was captured via closure, an alternative could also be to pass it explicitly via the `args` argument to `diffeqsolve`:


```python
class ForwardModel(eqx.Module):
  ...

  def vector_field(self, x):
    ...

  def __call__(self, t, x0):
    vector_field = lambda t, x, self: self.vector_field(x)
    term = dfx.ODETerm(vector_field)
    sol = dfx.diffeqsolve(term, ..., args=self)
    ...
```

**Comment by fhchl** [comment]
FYI: got another error message today

    TypeError: No constant handler for type: <class 'jax.interpreters.ad.JVPTracer'>

for _exactly same problem_, but using some newer version of either JAX (0.3.15) or diffrax (0.2.1). Took a while to debug ...
