### ISSUE TITLE
How to get number of step in backward solve ?

### ISSUE THREAD

**Issue by pablo2909** [patrick-kidger/diffrax#195]
Hello,

I was wondering if there is a way to get the number of function evaluation in the backward step when using `diffrax.BacksolveAdjoint` ? Is it also possible to log numerical error during a solve (forward and backward) ? 

Apologies if I am asking an obvious question :) 

Thank you for any help ! :)

**Comment by patrick-kidger** [comment]
Unfortunately there's no way to access the statistics of the backward solve. Right now JAX doesn't really provide any API we can use to return auxiliary information from the backward pass. (Although that may change soon-ish.)

---

In terms of logging numerical error: do you mean recording the error estimates? (E.g. the difference between the 4th and 5th order methods in an RK45 solver?) 

This is possible by implementing a wrapper for a solver (see #113). Although if you're running on the CPU then the in-place updates will probably trigger a known performance bug on that backend, in which the updated buffer is copied rather than having in-place updates made. (A fix for this will hopefully be landing in a month or so.)

**Comment by pablo2909** [comment]
Thank you for the speedy response. 

Looking forward for the changes to get auxiliary info form the backward pass then ! 

I haven't see #113 , I will read that ! :) 

Thank you !
