### ISSUE TITLE
How to implement a coupled SDE

### ISSUE THREAD

**Issue by rdaems** [patrick-kidger/diffrax#273]
Hi all,

What would be the proper way to implement this system of SDEs:

$dx(t) = a(t, x(t)) dt + \sum_i dy_i(t)$
$dy_i(t) = b_i(t, x(t), y_i(t)) dt + dW$

where all $y_i$ are driven by *the same* Brownian motion.

I have something like this, but I'm unsure if it's 100% correct:
```python
def drift(t, state, args):
    x, y = state
    y_dot = b(t, x, y)
    x_dot = a(t, x) + y_dot.sum()
    return (x_dot, y_dot)

def diffusion(t, state, args):
    x, y = state
    return (jnp.zeros_like(x), jnp.ones_like(y)[:, None])

brownian_shape = (
    jax.ShapeDtypeStruct((), jnp.float32),
    jax.ShapeDtypeStruct((1,), jnp.float32),
)
brownian_motion = VirtualBrownianTree(ts[0], ts[-1], tol=1e-3, shape=brownian_shape, key=key)
terms = MultiTerm(ODETerm(drift), ControlTerm(diffusion, brownian_motion))
```

This does not match exactly with my equations, since `y_dot.sum()` is already added to `x_dot` before adding the diffusion term to $dy_i(t)$. I can't find a way to do that, since $dy_i(t)$ depends on $x(t)$ ..

Any thoughts?

**Comment by anh-tong** [comment]
Hi, I wonder if your system of SDEs can be rewritten as following:

$dx(t) = a(t, x(t))dt + \sum_i b_i(t, x(t), y_i(t) dt +n dW_t$
$dy_i(t) = b_i(t, x(t), y_i(t)) dt + dW_t$

If this is the case, you may need to change the diffusion part with diffusion of the first equation as $n$ (the number of $y_i$)

```python
def diffusion(t, state, args):
    x, y = state
    return (y.shape[0] * jnp.one_like(x), jnp.ones_like(y))
```

However, because $dW_t$ is the same for all equations. I would think that we may extend `diffrax.AbstractPath` to make sure it return the same value with the right PyTree structure.

```python
from diffrax import AbstractPath, VirtualBrownianTree

class CustomPath(AbstractPath):
    
    n_y: int   # the number of y_i
    brownian_path: VirtualBrownianTree
    
    def __init__(self, t0, t1, tol, n_y, key):
        
        self.n_y = n_y
        self.brownian_path = VirtualBrownianTree(t0=t0,
                                                 t1=t1, 
                                                 tol=tol,
                                                 shape=(1,),  # assume that y_i is scalar
                                                 key=key)
        
    def evaluate(self, t0, t1=None, left: bool = True) -> PyTree:
        dW = self.brownian_path.evaluate(t0=t0, t1=t1, left=left)
        # return the PyTree structure like drift and diffusion
        return (dW, dW * jnp.ones(self.n_y))
```

What do you think?

**Comment by patrick-kidger** [comment]
@anh-tong is correct -- you should rewrite your SDE so that it's in the usual format.

And indeed if you want to have `state = (x, y)` as a pytree then you'll need to then have your brownian motion produce an output of the same structure, as they've done above.

Alternatively, here's a complete example in which `x` and `y` are concatenated together into a single array:
```python
import diffrax as dfx
import jax.numpy as jnp
import jax.random as jr

def a(t, x):
    return jnp.tanh(x)

def b(t, y, x):
    return jnp.tanh(y) + jnp.tanh(x)

def drift(t, state, args):
    x = state[0]
    y = state[1:]
    dy = b(t, x, y)
    dx = a(t, x) + dy.sum()
    return jnp.concatenate([dx[jnp.newaxis], dy])

def diffusion(t, state, args):
    x = state[0]
    y = state[1:]
    n = jnp.array([y.size], dtype=x.dtype)
    ones = jnp.ones_like(y)
    return jnp.concatenate([n, ones])

t0 = 0
t1 = 1
dt0 = 0.01
key = jr.PRNGKey(0)
bm = dfx.VirtualBrownianTree(t0, t1, tol=1e-3, shape=(), key=key)
term = dfx.MultiTerm(dfx.ODETerm(drift), dfx.ControlTerm(diffusion, bm))
solver = dfx.Euler()
x0 = jnp.array(1.)
y0 = jnp.array([2., 3., 4.])
state0 = jnp.concatenate([x0[jnp.newaxis], y0])
dfx.diffeqsolve(term, solver, t0, t1, dt0, state0)
```

**Comment by rdaems** [comment]
That are both excellent solutions. Thank you both!
