### ISSUE TITLE
wondering what's your take on diffeqpy

### ISSUE THREAD

**Issue by aldopareja** [patrick-kidger/diffrax#376]
Hi Patrick, recently bumped into [this colab](https://colab.research.google.com/drive/1bnQMdNvg0AL-LyPcXBiH10jBij5QUmtY?usp=sharing#scrollTo=MIpOCBu2Pz0C) and [an article](https://www.stochasticlifestyle.com/chatgpt-performs-better-on-julia-than-python-and-r-for-large-language-model-llm-code-generation-why/) that compares diffrax with diffeqpy and finds that diffeqpy is 10x faster than your jax-backed version!. 

This got me perplexed!!, how come some 10 stars repo built on top of some other 10 star repos performs so fast! (jk!, it's impressive work 😊). Wondering if you have also come across this and if you have any thoughts on the matter 😊

**Comment by patrick-kidger** [comment]
Haha! I have seen this. So diffeqpy is basically just a Python wrapper for Julia's DifferentialEquations.jl; part of their SciML ecosystem.

Broadly speaking, the two of us are in direct competition! They have DifferentialEquations.jl, LinearSolve.jl etc., and we have Diffrax, Lineax, etc.

I've written more about JAX vs Julia [here](https://kidger.site/thoughts/jax-vs-julia/). My overall feeling is that both options are "fast enough", so that I recommend making a choice between them based on other considerations:
- JAX integrates much more cleanly with the Python ecosystem (often important), and for similar reasons also tends to have better developer tooling. Julia is still weaker here.
- At least in the case Diffrax etc., we actually also offer stronger type safety: we use ABCs and pyright religiously. In contrast Julia has no analogus trait-like concept.
- JAX has a single strong autodifferentiation system. Julia is stil experimenting with ~10 different systems, none of which really seem to have widespread adoption/support.
- Julia tends to have more features! If you need to do something obscure then they've probably implemented it and we maybe haven't.
- Julia is "more elegant": it's a single fast language, not a JIT-compiler crammed into a slow language.
- JAX tends to be much less buggy. We take correctness pretty seriously; in contrast Julia is notorious for having a lot of silent correctness issues.

To bring this full circle and touch on the post you mentioned -- I did actually verify some of their microbenchmarks, and they really are faster! Unfortunately, I also found some bugs whilst doing so. This more or less tracked my usual experience above.

Ultimately, I should emphasise that we're all friends. I frequently hang out with Julia folks, and I like to think that our little competition pushes us both to be better!

**Comment by aldopareja** [comment]
@xukai92
