### ISSUE TITLE
Multi device parallelism

### ISSUE THREAD

**Issue by lockwo** [patrick-kidger/diffrax#403]
If we wanted to parallelize my SDE integration across devices, previously I would just `pmap` across keys and y0s. However, I see the shard mapping is the way of the future of jax, so is the recommended/best way to do this in diffrax to shard the keys and y0s and `eqx.filter_shard` them like in https://docs.kidger.site/equinox/examples/parallelism/?

Something like 

```python
@eqx.filter_jit
@eqx.filter_vmap
def solve(key, y0):
    brownian(key)
    sol = diffeqsolve(terms, y0, ...)
    return sol.ys

num_devices = len(jax.devices())
devices = mesh_utils.create_device_mesh((num_devices, 1))
sharding = jshard.PositionalSharding(devices)

keys = jax.random.split(jax.random.PRNGKey(0), 10000)
y0s = jax.random.uniform(keys[0], shape=(10000, 5))

k, y = eqx.filter_shard((keys, y0s), sharding)
parallelized_solutions = solve(k, y)
```

**Comment by patrick-kidger** [comment]
Broadly speaking, I think so!

That said, last I checked I think there was still some funny business with this due to sharding not knowing how to interact with `eqx.error_if`. In case you bump into this, then some reference points on this:
- [This](https://github.com/patrick-kidger/equinox/pull/342/files) is a draft PR adding `custom_partitioning` support for `error_if`. I never finished this due to some JAX bugs at the time (`custom_partitioning` had only just been introduced); I'd be happy to see a PR fixing this up.
- [This](https://github.com/patrick-kidger/diffrax/issues/247#issuecomment-1538718786) may be a useful reference which got this working before.
- If all else fails, then `eqx.error_if` can be disabled (globally for all runtime errors!) with `EQX_ON_ERROR=nan`. That's not super safe, of course.

**Comment by lockwo** [comment]
This is a broader question, something I noticed in equinox as well, is that when I just run some timing experiments with 1 CPU device vmap, 10 CPU devices pmap, and 10 CPU device shard, the pmap is about 5-10x faster (as expected) and the sharing is about >10x slower than vmap (or pmap). Is this some obvious CPU thing or a normal rookie mistake in some implementation? I will make a new issue (probably in equinox with MVC) but I was curious if you've ever encountered this before?
