### ISSUE TITLE
Un-pin `typeguard`

### ISSUE THREAD

**Issue by dhirschfeld** [patrick-kidger/diffrax#421]
https://github.com/patrick-kidger/diffrax/blob/80d1f34f7608629246600831f9397eb6fc5973a3/pyproject.toml#L26

Why is `typeguard` pinned to an exact version, especially one that is so old?

It's generally considered very bad packaging practice to pin to exact versions as it's ~never required and prevents getting even security patches without publishing a new release.

Also, it's ancient and won't be getting any updates - current HEAD is 4.2.1:

![image](https://github.com/patrick-kidger/diffrax/assets/881019/aedd5652-d344-4864-8644-1555088559b9)

![image](https://github.com/patrick-kidger/diffrax/assets/881019/1c751fd2-6132-413a-b575-c4900329d5b8)

_Originally posted by @dhirschfeld in https://github.com/patrick-kidger/diffrax/pull/364#discussion_r1606119591_

**Comment by dhirschfeld** [comment]
* https://github.com/agronholm/typeguard
* https://pypi.org/project/typeguard/#history

**Comment by patrick-kidger** [comment]
This is intentional. You'll notice jaxtyping is also pinned to the same version.

See threads like https://github.com/patrick-kidger/jaxtyping/pull/124#issuecomment-1763569347 and https://github.com/agronholm/typeguard/issues/353. The quick summary is that later versions of typeguard seem to do things that are incompatible with jaxtyping etc.

**Comment by dhirschfeld** [comment]
Thanks for the explanation! And the references :heart:

Hopefully the issue can eventually be resolved upstream...

**Comment by aowenson-imm** [comment]
A solution is possible: #579
