### ISSUE TITLE
[question] How to implement Runge--Kutta order 4 

### ISSUE THREAD

**Issue by puat133** [patrick-kidger/diffrax#426]
Hi,

I'm enjoying using Diffrax for my current application! At the moment, I'm looking for a simple Runge-Kutta order 4 implementation in Diffrax but haven't been able to find one. I assume I'll need to create a custom ODE solver class by inheriting the `AbstractERK` class.

Regarding the ButcherTableau, I have the values for `a_lower`,` b_sol`, and `c` from the standard RK-4 Butcher Tableau, but I'm unsure about the `b_error` value. Am I missing something here?

Thanks for your help!

**Comment by patrick-kidger** [comment]
So I've never implemented this just because `Tsit5` is generally a stronger choice than either of the two common `RK4`s, so it just never seemed important to include!

So `b_error` is an embedded error estimate. The solution of the step is given by linearly combining the stages using `b_sol`, and the error of the step is given by linearly combining the stages using `b_error`. (Notably *not* by computing `(b_error - b_sol) @ stages` as many other implementations do; we instead fold the subtraction into the definition of `b_error` in the first place.)

You have a few options:
- Just use the built-in `Tsit5` instead.
- Use whatever your favourite error estimator is for RK4.
- Fill in a dummy `b_error=array of zeros` -- but note that the resulting solver will silently fail if used in conjunction with `diffrax.PIDController`! It can only be used with fixed step size controllers.
- Offer a PR against Diffrax so that `b_error=None` is valid, and if used will disable the error estimator altogether. (This should be fairly simple, happy to offer guidance if this is what you prefer.) This will result in things loudly failing if the solver is used in conjunction with `diffrax.PIDController`.

I hope that helps!

**Comment by puat133** [comment]
Thanks for the reply!

I just realized that it's possible to have a fixed time step in `Tsit5()` as well as `Dorpri5()`. I thought these always required a `PIDController`. ^^

Regarding the standard RK4, I still want to create this simple ODE solver. I'll look for a suitable error estimator and try to implement it.

Thanks again for your help!
