### ISSUE TITLE
Logging metrics during an ODE solve

### ISSUE THREAD

**Issue by nicholasjng** [patrick-kidger/diffrax#60]
Hello @patrick-kidger,

thank you for open-sourcing this nice library! I was going to resume work on my own small ODE lib, but since this is much more elaborate than what I came up with so far, I am inclined to use this instead for a small project in the future.

One question that came up to me when reading the source code: Is there currently a way to compute step-wise metrics during the solve? (Think logging step sizes, Jacobian eigenvalues, etc.)

This would presumably happen in the `integrate` method. Could I e.g. use the `solver_state` pytree for this in, say, overridden solver classes? Thank you for your consideration.

**Comment by patrick-kidger** [comment]
Yep, `solver_state` is probably the thing to do, as long as what you need to record is `O(1)` in the number of steps. (And not `O(num steps)`.) i.e. as long as you're updating information rather than appending information.

You could do something like (untested):

```python
import diffrax

class MetricSolver(diffrax.AbstractWrappedSolver):
    @property
    def term_structure(self):
        return self.solver.term_structure

    def order(self, terms):  # used for ODEs
        return self.solver.order(terms)

    def strong_order(self, terms):  # used for SDEs
        return self.solver.strong_order(terms)

    def error_order(self, terms):  # used for adaptive stepping
        return self.solver.error_order(terms)

    def init(self, terms, t0, t1, y0, args):
        solver_state = self.solver.init(terms, t0, t1, y0, args)
        metric_state = ...   # initialise your metrics here
        return (solver_state, metric_state)

    def step(self, terms, t0, t1, y0, args, state, made_jump):
        solver_state, metric_state = state
        y1, y_error, dense_info, solver_state, result = self.solver.step(terms, t0, t1, y0, args, state, made_jump)
        metric_state = ...  # update your metrics here
        state = (solver_state, metric_state)
        return y1, y_error, dense_info, state, result

solver = MetricSolver(diffrax.Tsit5())  # using Tsit5 as an example
```

As you can see, Diffrax provides `AbstractWrappedSolver` as an abstract base class when wrapping another solver.`*` By default subclasses take a single argument; the solver to be wrapped. You can see that this is the `self.solver` attribute used in the code.

(FWIW the above is quite a lot of boiler plate, which could be reduced by having `AbstractWrappedSolver` forward `term_structure`, `order,` `strong_order`, `error_order` by default -- instead of having to write it out as above. I'll use this issue to track that feature.)

`*` Whenever Diffrax needs to inspect the solver (e.g. to check if it supports adaptive step sizing), it knows to check inside of `AbstractWrappedSolver`s.

**Comment by patrick-kidger** [comment]
An `O(n)` solution is surprisingly tricky to accomplish within JAX. You do have a few options.

Probably the simplest thing to do is make `metric_state` be a buffer `O(n)` in size, and then make in-place updates to it as the solve progresses. However, due to several limitations in JAX, this will only compile away to true in-place updates if at least one of the following is true:
- You use baked-in constant step sizes: `stepsize_controller=ConstantStepSize(compile_steps=True)`;
- You are happy not to backpropagate: `adjoint=NoAdjoint()`;
- You are happy to only backpropagate via optimise-then-discretise: `adjoint=BacksolveAdjoint()`.

You may be wondering why these weird-looking restrictions? The short version is that it's quite difficult to backpropagate through the computation graph produced when using adaptive step size solvers. You don't know how many steps an adaptive solver will make in advance, so you "have to" use `lax.while_loop` over `lax.scan`. But `lax.while_loop` doesn't support backpropagation.

Now in practice Diffrax does a bunch of custom stuff to make backprop-through-adaptive-steps happen anyway, but it's quite fragile, and has to navigate several performance bugs in either JAX or XLA -- in particular performance bugs to do with in-place updates.

Let me know if any of the above three options are suitable for you. If they're not then I can give you some other suggestions, but as per these fundamental limitations of JAX, they just might be a bit more involved!

**Comment by nicholasjng** [comment]
Thank you for the write-up! I've seen most of your JAX threads concerning Jaxpr building efficiency and limitations, so I believe I understand where you are coming from with the limitations aspect of Jax/Jaxlib.

My naive algorithm would have been something like Jax's experimental `odeint`, which uses while loops *inside* the `body_fun`, to retry stepping for a number of times until the next acceptable step is made. (So, technically, it is a grid-evaluation of the ODE but with adaptive stepping between grid points)

In that case, I believe, even though a while loop is technically involved, the only thing that matters for the gradient is the actual accepted state, so in that model, the while-loop should technically be eligible to be DCE'd from the backward pass.

But I can very much imagine that theory and reality may differ substantially in this case, which I'm guessing is also the reason for all of this extra work you did. (Maybe this kind of algorithm could be where a custom Jaxpr interpreter working out the backward pass could finally be necessary?)

I will try out the options you mentioned. Looks like the inplace update is the bottleneck, then.

**Comment by nicholasjng** [comment]
What I meant was that you should be able to calculate the gradient of the ODE solve solely from the accepted steps (i.e., the return value of the while-loops), and not the rejected ones that are thrown away. But as it turns out, I was conflating the numerical gradient (which I had in mind) from the intermediate steps with the autodiff of the Jaxpr (which would contain the `while_loop`s, anyway, making bwd-diff-mode impossible as I understand).

Also, I hadn't even thought of `vmap` at all yet. Good to know that the intermediate while-loop approach does not play nicely with batching, then.

Lastly, do you have a literature tip on the discretize-then optimize strategy? I admit, until now, for me ODE backprop was more or less synonymous with the adjoint dynamics solve from the NODE paper. Thank you for your patience with my questions, by the way :)

**Comment by patrick-kidger** [comment]
> (FWIW the above is quite a lot of boiler plate, which could be reduced by having AbstractWrappedSolver forward term_structure, order, strong_order, error_order by default -- instead of having to write it out as above. I'll use this issue to track that feature.)

Having thought about this some more, I've decided against doing this. (Which is what this issue was kept open to track.) If we look at `diffrax.HalfSolver` by way of example, we see that it also forwards `init`, `interpolation_cls`, and `func_for_init`, which arguably we should all forward by default as well. So it kind of becomes a matter of forward-everything-by-default or forward-nothing-by-default. I'm thus inclined towards the latter on the basis of failing loudly rather than failing silently.

**Comment by patrick-kidger** [comment]
It goes without saying -- please still feel free to leave any questions or comments wrt the initial point of this issue, about how to log metrics during the ODE solve.

**Comment by pharringtonp19** [comment]
@patrick-kidger -- Awesome library

In this context of "logging-metrics", I was wondering how one might go about implementing [Learning Differential Equations that are Easy to Solve](https://arxiv.org/abs/2007.04504). My naive implementation "appended" the regularizing term to the state. However, from [discussions](https://github.com/jacobjinkelly/easy-neural-ode/issues/5) with one of the authors, they suggest a more efficient way to implement it.

> we actually only need to integrate the regularization term on the backwards pass - on the forwards pass we can just integrate a placeholder value of 0. This is essentially because we only care about the gradient with respect to the regularization term, and the gradient of the regularization can be constructed from the value of the rest of the state (everything but the regularization) and its gradient.

Do you have any suggestions on how to tackle this with diffrax? -- happy to open a separate issue if you would prefer.

**Comment by patrick-kidger** [comment]
So these are an example of an "integral loss" (or regularisation term): a loss of the form `\int k(y(t)) dt` for some function `k`. Indeed it's a known trick to avoid calculating these on the forward pass, and only calculate their gradients on the backward pass.

(In practice this is pretty much only ever possible when using a custom backward pass like `BacksolveAdjoint` though. I don't think any autodifferentiation framework, JAX or otherwise, is currently smart enough to elide the forward pass if using the "standard" `RecursiveCheckpointAdjoint`.)

Right now the best way to tackle this in Diffrax is indeed just to append these values during the forward calculation. Even with other libraries, I think people have often had to really know what they're doing and then hack something together, since it's such an edge-case in terms of autodifferentiation frameworks.

I've opened #69 to track this though, as this would be nice to have.
CC @jacobjinkelly
CC @Zymrael as I recall you have something like in torchdyn?
