### ISSUE TITLE
dt0 is mandatory even for solvers that support adaptive time stepping

### ISSUE THREAD

**Issue by ma-sadeghi** [patrick-kidger/diffrax#83]
Running the following script:
```python
from diffrax import diffeqsolve, ODETerm, Dopri5
import jax.numpy as jnp

def f(t, y, args):
    return -y

term = ODETerm(f)
solver = Tsit5()
y0 = jnp.array([2., 3.])
solution = diffeqsolve(term, solver, t0=0, t1=1, dt0=None, y0=y0)
```

leads to the following exception:
```python
ValueError: Constant step size solvers cannot select step size automatically; please pass a value for `dt0`.
```

**Comment by patrick-kidger** [comment]
That's because `diffeqsolve` uses constant step sizes (equal to `dt0`) by default. If you want adaptive time stepping then pass in an adaptive step size controller: `diffeqsolve(..., stepsize_controller=PIDController(rtol=..., atol=...))`.

Adaptivity and choice of solver are two different things, despite being commonly conflated.

**Comment by ma-sadeghi** [comment]
Great, thank you so much for clarification. It makes absolute sense.
