### ISSUE TITLE
Wrong coefficients in Tsit5 error estimate?

### ISSUE THREAD

**Issue by martenlienen** [patrick-kidger/diffrax#98]
Hey Patrick,

I was checking out your implementation of Tsit5 and I think `b_error` might be wrong.

https://github.com/patrick-kidger/diffrax/blob/c886c218fa300ca5d7037405703c6ae568a80aab/diffrax/solver/tsit5.py#L68-L84

If we compare to [the paper](https://www.sciencedirect.com/science/article/pii/S0898122111004706), we see that the coefficients to be subtracted are different from the b-tilde coefficients. The issue might stem from the confusing fact that they had originally put the final error coefficients (b - b_tilde) as b in OrdinaryDiffEq.jl, I think. Now they store the b-tilde coefficients as b-tilde which makes it easier to understand what is going on but for some reason they opted to flip the signs of all coefficients now?

https://github.com/SciML/OrdinaryDiffEq.jl/blob/1de2a573a93988ad703018896b04756ef98a0d10/src/tableaus/low_order_rk_tableaus.jl#L584-L597

Best,
Marten

**Comment by martenlienen** [comment]
Also, something weird is going on with the signs in the julia implementation, I believe https://github.com/SciML/OrdinaryDiffEq.jl/issues/1654

**Comment by patrick-kidger** [comment]
Hey Marten,

I think the implementation is correct as-is. I belive Tsitouras' paper uses b-tilde in two different ways: first to denote the coefficients of the embedded solution; second to the denote the coefficients of the error estimate. (Both conventions are used in the broader literature.)

In particular, the values for b-tilde given in Tsitouras' paper match those of our b-error (i.e. the second convention):
```python
>>> diffrax.Tsit5.tableau.b_error
array([ 0.00178001,  0.00081643, -0.00788088,  0.14471101, -0.58235717, 0.45808211, -0.01515152])
```
at least up to the sign of the last value, which as Chris notes in the other thread has a typo.

We can verify things -- both our b-tilde interpretation, and the sign of the final coefficient -- by evaluating `sum(diffrax.Tsit5.tableau.b_error)`, which on my machine produces `-1.249000902703301e-16`. Error coefficients essentially always have the property that their sum should be zero. This is because they are typically constructed as a difference of two solutions, and the sum-of-coefficients for a solution should be one, as they construct a solution through a convex combination of stages. (Check: `sum(diffrax.Tsit5.tableau.b_sol)` produces `0.9999999999999998`.)

**Comment by martenlienen** [comment]
Thanks a lot! I am not too familiar with these numerical methods papers, so I got confused when they changed the meaning of b-tilde without saying so. While working out the kinks in my own implementation, I just discovered basically what you described in your comment, though it took me a bit to understand what is going on.
